from .models import *
from django.contrib import admin
# Register your models here.
admin.site.register(News)
admin.site.register(News2)
admin.site.register(Slide)
admin.site.register(Complaint)
admin.site.register(Suggestion)
admin.site.register(Location)
admin.site.register(Phone)
admin.site.register(Agriculture_Suggestion)
admin.site.register(Industrial_Suggestion)
admin.site.register(Development_Suggestion)
admin.site.register(Service_Suggestion)
admin.site.register(Tourist_Suggestion)
admin.site.register(Organization_Task)
admin.site.register(Organization_Leader)
admin.site.register(Organization_Governing_Council)
admin.site.register(Organization_Law)
admin.site.register(Project_Ended)
admin.site.register(Project_UnderProcessing)
admin.site.register(Project_Planned)
admin.site.site_header = ('لوحة تحكم هيئة تنمية الصعيد')
admin.site.site_title = ('هيئة تنمية الصعيد')
admin.site.index_title = ('هيئة تنمية الصعيد')