# Generated by Django 2.2 on 2019-04-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(help_text='Enter news title', max_length=200)),
                ('newsImg', models.ImageField(help_text='Enter field doc', upload_to='')),
                ('newsContent', models.TextField(help_text='Enter news content')),
            ],
            options={
                'ordering': ['-newsTitle'],
            },
        ),
    ]
