# Generated by Django 2.2 on 2019-04-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['newsTitle', 'newsImg', 'newsContent']},
        ),
    ]
