# Generated by Django 2.2 on 2019-04-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190422_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_Img',
            field=models.ImageField(help_text='Enter field doc', upload_to='static/img'),
        ),
    ]
