# Generated by Django 2.2 on 2019-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190423_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_imgloc',
            field=models.TextField(default='img'),
        ),
    ]
