# Generated by Django 2.2 on 2019-04-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_news_news_imgloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_imgloc',
            field=models.TextField(default='<django.db.models.fields.files.ImageField>'),
        ),
    ]
