# Generated by Django 2.2 on 2019-04-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190423_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_imgloc',
            field=models.TextField(default=None),
        ),
    ]
