# Generated by Django 2.2 on 2019-04-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190423_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_imgloc',
        ),
    ]
