# Generated by Django 2.2 on 2019-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_news_news_imgloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_Img',
            field=models.ImageField(help_text='Upload Image', upload_to='img'),
        ),
    ]
