# Generated by Django 2.2 on 2019-04-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190423_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_img', models.ImageField(help_text='Upload SlideShow Image', upload_to='home/static/img/slideShow')),
            ],
            options={
                'ordering': ['slide_img'],
            },
        ),
    ]
