# Generated by Django 2.2 on 2019-04-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_caption',
            field=models.CharField(default='Caption Text', help_text='Enter Image Caption', max_length=200),
        ),
    ]
