# Generated by Django 2.2 on 2019-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_slide_slide_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_album',
            field=models.CharField(default='Tourist Album', help_text='Enter the album name', max_length=200),
        ),
    ]
