# Generated by Django 2.2 on 2019-04-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_slide_slide_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_title', models.CharField(default='suggestion', help_text='Suggestion title', max_length=500)),
                ('suggestion_writer', models.CharField(default='Visitor', help_text="Suggestion writer's name", max_length=200)),
                ('suggestion_email', models.EmailField(help_text="Suggestion writer's email", max_length=254)),
                ('suggestion_date', models.DateTimeField(blank=True, help_text='The suggestion Date', null=True)),
                ('suggestion_content', models.TextField(help_text='Suggestion content')),
            ],
            options={
                'ordering': ['suggestion_title'],
            },
        ),
    ]
