# Generated by Django 2.2 on 2019-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190427_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_title',
            field=models.CharField(default='suggestion', help_text='عنوان الإقتراح', max_length=500),
        ),
    ]
