# Generated by Django 2.2 on 2019-04-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190429_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_writer',
            field=models.CharField(help_text="Suggestion writer's name", max_length=200),
        ),
    ]
