# Generated by Django 2.2 on 2019-04-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190429_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='مكان الهيئة', max_length=500)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_content',
            field=models.TextField(default='محتوى الإقتراح ...'),
        ),
    ]
