# Generated by Django 2.2 on 2019-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190429_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='تليفونات الهيئة', max_length=200)),
            ],
            options={
                'ordering': ['phone'],
            },
        ),
    ]
