# Generated by Django 2.2 on 2019-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculture_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم المقترح', max_length=500)),
                ('content', models.TextField(default='محتوى الإقتراح ...')),
            ],
            options={
                'ordering': ['title', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Development_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم المقترح', max_length=500)),
                ('content', models.TextField(default='محتوى الإقتراح ...')),
            ],
            options={
                'ordering': ['title', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Industrial_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم المقترح', max_length=500)),
                ('content', models.TextField(default='محتوى الإقتراح ...')),
            ],
            options={
                'ordering': ['title', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Service_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم المقترح', max_length=500)),
                ('content', models.TextField(default='محتوى الإقتراح ...')),
            ],
            options={
                'ordering': ['title', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Tourist_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اسم المقترح', max_length=500)),
                ('content', models.TextField(default='محتوى الإقتراح ...')),
            ],
            options={
                'ordering': ['title', 'content'],
            },
        ),
    ]
