# Generated by Django 2.2 on 2019-04-29 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_agriculture_suggestion_development_suggestion_industrial_suggestion_service_suggestion_tourist_sugge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 29, 21, 48, 31, 684976), help_text='التاريخ', null=True),
        ),
    ]
