# Generated by Django 2.2 on 2019-04-30 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190429_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oraginzation_Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_leader', models.CharField(help_text='قيادات الهيئة', max_length=300)),
            ],
            options={
                'ordering': ['organization_leader'],
            },
        ),
        migrations.CreateModel(
            name='Organization_Governing_Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='اللقب', max_length=300)),
                ('name', models.CharField(help_text='الاسم', max_length=400)),
            ],
            options={
                'ordering': ['title', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Organization_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_task', models.TextField(help_text='مهام الهيئة')),
            ],
            options={
                'ordering': ['organization_task'],
            },
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 30, 14, 18, 36, 861177), help_text='التاريخ', null=True),
        ),
    ]
