# Generated by Django 2.2 on 2019-04-30 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190430_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oraginzation_Leader',
            new_name='Organization_Leader',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 30, 14, 21, 17, 71192), help_text='التاريخ', null=True),
        ),
    ]
