# Generated by Django 2.2 on 2019-04-30 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190430_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Ended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='اسم المشروع', max_length=500)),
                ('project_description', models.TextField(help_text='وصف المشروع')),
            ],
            options={
                'ordering': ['project_name', 'project_description'],
            },
        ),
        migrations.CreateModel(
            name='Project_Planned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='اسم المشروع', max_length=500)),
                ('project_description', models.TextField(help_text='وصف المشروع')),
            ],
            options={
                'ordering': ['project_name', 'project_description'],
            },
        ),
        migrations.CreateModel(
            name='Project_UnderProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='اسم المشروع', max_length=500)),
                ('project_description', models.TextField(help_text='وصف المشروع')),
            ],
            options={
                'ordering': ['project_name', 'project_description'],
            },
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 30, 16, 14, 18, 153284), help_text='التاريخ', null=True),
        ),
    ]
