# Generated by Django 2.2 on 2019-04-30 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20190430_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 30, 16, 21, 24, 675023), help_text='التاريخ', null=True),
        ),
    ]
