# Generated by Django 2.2 on 2019-05-01 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20190430_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_title', models.CharField(help_text='عنوان الشكوى', max_length=500, verbose_name='عنوان الشكوى')),
                ('Complaint_writer', models.CharField(help_text='اسم المواطن', max_length=200, verbose_name='اسم المواطن')),
                ('Complaint_email', models.EmailField(help_text='البريد الإلكتروني', max_length=254, verbose_name='البريد الإلكتروني')),
                ('Complaint_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 15, 18, 46, 211486), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ')),
                ('Complaint_content', models.TextField(default='محتوى الشكوى ...', verbose_name='محتوى الشكوى')),
            ],
            options={
                'verbose_name': 'شكاوى المواطنين',
                'verbose_name_plural': 'شكاوى المواطنين',
                'ordering': ['Complaint_title', 'Complaint_writer', 'Complaint_email', 'Complaint_date', 'Complaint_content'],
            },
        ),
        migrations.AlterModelOptions(
            name='agriculture_suggestion',
            options={'ordering': ['title', 'content'], 'verbose_name': 'مقترحات زراعية', 'verbose_name_plural': 'مقترحات زراعية'},
        ),
        migrations.AlterModelOptions(
            name='development_suggestion',
            options={'ordering': ['title', 'content'], 'verbose_name': 'مقترحات تنموية', 'verbose_name_plural': 'مقترحات تنموية'},
        ),
        migrations.AlterModelOptions(
            name='industrial_suggestion',
            options={'ordering': ['title', 'content'], 'verbose_name': 'مقترحات صناعية', 'verbose_name_plural': 'مقترحات صناعية'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location'], 'verbose_name': 'مكان الهيئة', 'verbose_name_plural': 'مكان الهيئة'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['news_Title', 'news_Img', 'news_Content'], 'verbose_name': 'أخبار أهل الصعيد', 'verbose_name_plural': 'أخبار أهل الصعيد'},
        ),
        migrations.AlterModelOptions(
            name='news2',
            options={'ordering': ['news_Title', 'news_Img', 'news_Content'], 'verbose_name': 'أخبار الهيئة', 'verbose_name_plural': 'أخبار الهيئة'},
        ),
        migrations.AlterModelOptions(
            name='organization_governing_council',
            options={'ordering': ['title', 'name'], 'verbose_name': 'مجلس الإدارة', 'verbose_name_plural': 'مجلس الإدارة'},
        ),
        migrations.AlterModelOptions(
            name='organization_law',
            options={'ordering': ['law_title', 'law_date', 'law_content'], 'verbose_name': 'قوانين ولوائح', 'verbose_name_plural': 'قوانين ولوائح'},
        ),
        migrations.AlterModelOptions(
            name='organization_leader',
            options={'ordering': ['organization_leader'], 'verbose_name': 'قيادات الهيئة', 'verbose_name_plural': 'قيادات الهيئة'},
        ),
        migrations.AlterModelOptions(
            name='organization_task',
            options={'ordering': ['organization_task'], 'verbose_name': 'مهام الهيئة', 'verbose_name_plural': 'مهام الهيئة'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['phone'], 'verbose_name': 'تليفونات الهيئة', 'verbose_name_plural': 'تليفونات الهيئة'},
        ),
        migrations.AlterModelOptions(
            name='project_ended',
            options={'ordering': ['project_name', 'project_description'], 'verbose_name': 'مشروعات تم تنفيذها', 'verbose_name_plural': 'مشروعات تم تنفيذها'},
        ),
        migrations.AlterModelOptions(
            name='project_planned',
            options={'ordering': ['project_name', 'project_description'], 'verbose_name': 'مشروعات مخططه', 'verbose_name_plural': 'مشروعات مخططه'},
        ),
        migrations.AlterModelOptions(
            name='project_underprocessing',
            options={'ordering': ['project_name', 'project_description'], 'verbose_name': 'مشروعات تحت التنفيذ', 'verbose_name_plural': 'مشروعات تحت التنفيذ'},
        ),
        migrations.AlterModelOptions(
            name='service_suggestion',
            options={'ordering': ['title', 'content'], 'verbose_name': 'مقترحات خدمية', 'verbose_name_plural': 'مقترحات خدمية'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['slide_img'], 'verbose_name': 'معرض الصور', 'verbose_name_plural': 'معرض الصور'},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['suggestion_title', 'suggestion_writer', 'suggestion_email', 'suggestion_date', 'suggestion_content'], 'verbose_name': 'مقترحات المواطنين', 'verbose_name_plural': 'مقترحات المواطنين'},
        ),
        migrations.AlterModelOptions(
            name='tourist_suggestion',
            options={'ordering': ['title', 'content'], 'verbose_name': 'مقترحات سياحية', 'verbose_name_plural': 'مقترحات سياحية'},
        ),
        migrations.AlterField(
            model_name='agriculture_suggestion',
            name='content',
            field=models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح'),
        ),
        migrations.AlterField(
            model_name='agriculture_suggestion',
            name='title',
            field=models.CharField(help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح'),
        ),
        migrations.AlterField(
            model_name='development_suggestion',
            name='content',
            field=models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح'),
        ),
        migrations.AlterField(
            model_name='development_suggestion',
            name='title',
            field=models.CharField(help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح'),
        ),
        migrations.AlterField(
            model_name='industrial_suggestion',
            name='content',
            field=models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح'),
        ),
        migrations.AlterField(
            model_name='industrial_suggestion',
            name='title',
            field=models.CharField(help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(help_text='مكان الهيئة', max_length=500, verbose_name='مكان الهيئة'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_Content',
            field=models.TextField(help_text='أدخل محتوى الخبر', verbose_name='محتوى الخبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_Date',
            field=models.DateTimeField(blank=True, help_text='أدخل الوقت والتاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_Img',
            field=models.ImageField(help_text='قم بتحميل صورة الخبرة', upload_to='home/static/img', verbose_name='صورة الخبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_Title',
            field=models.CharField(help_text='أدخل عنوان الخبر', max_length=200, verbose_name='عنوان الخبر'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='news_Content',
            field=models.TextField(help_text='أدخل محتوى الخبر', verbose_name='محتوى الخبر'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='news_Date',
            field=models.DateTimeField(blank=True, help_text='أدخل الوقت والتاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='news_Img',
            field=models.ImageField(help_text='قم بتحميل صورة الخبرة', upload_to='home/static/img', verbose_name='صورة الخبر'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='news_Title',
            field=models.CharField(help_text='أدخل عنوان الخبر', max_length=200, verbose_name='عنوان الخبر'),
        ),
        migrations.AlterField(
            model_name='organization_governing_council',
            name='name',
            field=models.CharField(help_text='الاسم', max_length=400, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='organization_governing_council',
            name='title',
            field=models.CharField(help_text='اللقب', max_length=300, verbose_name='اللقب أو الدرجة'),
        ),
        migrations.AlterField(
            model_name='organization_law',
            name='law_content',
            field=models.FileField(help_text='ملف الوثيقة', upload_to='', verbose_name='ملف الوثيقة'),
        ),
        migrations.AlterField(
            model_name='organization_law',
            name='law_date',
            field=models.DateField(help_text='التاريخ', verbose_name='تاريخ الوثيقة'),
        ),
        migrations.AlterField(
            model_name='organization_law',
            name='law_title',
            field=models.CharField(help_text='الوثيقة', max_length=1000, verbose_name='عنوان الوثيقة'),
        ),
        migrations.AlterField(
            model_name='organization_leader',
            name='organization_leader',
            field=models.CharField(help_text='قيادات الهيئة', max_length=300, verbose_name='قيادات الهيئة'),
        ),
        migrations.AlterField(
            model_name='organization_task',
            name='organization_task',
            field=models.TextField(help_text='مهام الهيئة', verbose_name='مهام الهيئة'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(help_text='تليفونات الهيئة', max_length=200, verbose_name='تليفونات الهيئة'),
        ),
        migrations.AlterField(
            model_name='project_ended',
            name='project_description',
            field=models.TextField(help_text='وصف المشروع', verbose_name='وصف المشروع'),
        ),
        migrations.AlterField(
            model_name='project_ended',
            name='project_name',
            field=models.CharField(help_text='اسم المشروع', max_length=500, verbose_name='اسم المشروع'),
        ),
        migrations.AlterField(
            model_name='project_planned',
            name='project_description',
            field=models.TextField(help_text='وصف المشروع', verbose_name='وصف المشروع'),
        ),
        migrations.AlterField(
            model_name='project_planned',
            name='project_name',
            field=models.CharField(help_text='اسم المشروع', max_length=500, verbose_name='اسم المشروع'),
        ),
        migrations.AlterField(
            model_name='project_underprocessing',
            name='project_description',
            field=models.TextField(help_text='وصف المشروع', verbose_name='وصف المشروع'),
        ),
        migrations.AlterField(
            model_name='project_underprocessing',
            name='project_name',
            field=models.CharField(help_text='اسم المشروع', max_length=500, verbose_name='اسم المشروع'),
        ),
        migrations.AlterField(
            model_name='service_suggestion',
            name='content',
            field=models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح'),
        ),
        migrations.AlterField(
            model_name='service_suggestion',
            name='title',
            field=models.CharField(help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_album',
            field=models.CharField(default='Tourist Album', help_text='أدخل اسم الألبوم(مثال : سياحية - فرعونية - إسلامية - قبطية  وهكذا ...)', max_length=200, verbose_name='اسم الألبوم'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_caption',
            field=models.CharField(default='Caption Text', help_text='اكتب التعليق - التعقيب أسفل الصورة', max_length=200, verbose_name='تعليق على الصورة'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_img',
            field=models.ImageField(help_text='قم برفع الصورة', upload_to='home/static/img/slideShow', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_content',
            field=models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 15, 18, 46, 211486), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_email',
            field=models.EmailField(help_text='البريد الإلكتروني', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_title',
            field=models.CharField(help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_writer',
            field=models.CharField(help_text='اسم المواطن', max_length=200, verbose_name='اسم المواطن'),
        ),
        migrations.AlterField(
            model_name='tourist_suggestion',
            name='content',
            field=models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح'),
        ),
        migrations.AlterField(
            model_name='tourist_suggestion',
            name='title',
            field=models.CharField(help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح'),
        ),
    ]
