# Generated by Django 2.2 on 2019-05-01 13:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20190501_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['Complaint_id', 'Complaint_title', 'Complaint_writer', 'Complaint_writer_id', 'Complaint_writer_phone', 'Complaint_email', 'Complaint_date', 'Complaint_content'], 'verbose_name': 'شكاوى المواطنين', 'verbose_name_plural': 'شكاوى المواطنين'},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='Complaint_id',
            field=models.UUIDField(default=uuid.UUID('42478ed3-c67e-4415-8cb5-0451a4d743de'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='Complaint_writer_id',
            field=models.CharField(default=1, help_text='الرقم القومي', max_length=200, verbose_name='الرقم القومي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='Complaint_writer_phone',
            field=models.CharField(default=2, help_text='رقم الهاتف', max_length=200, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 15, 39, 20, 872334), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 15, 39, 20, 872334), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
    ]
