# Generated by Django 2.2 on 2019-05-01 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20190501_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['Complaint_title', 'Complaint_writer', 'Complaint_writer_id', 'Complaint_writer_phone', 'Complaint_email', 'Complaint_date', 'Complaint_content'], 'verbose_name': 'شكاوى المواطنين', 'verbose_name_plural': 'شكاوى المواطنين'},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='Complaint_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 16, 35, 54, 542582), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 16, 35, 54, 542582), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
    ]
