# Generated by Django 2.2 on 2019-05-01 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20190501_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 18, 22, 8, 249416), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 18, 22, 8, 249416), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
    ]
