# Generated by Django 2.2 on 2019-05-02 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20190502_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 11, 25, 52, 738102), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 11, 25, 52, 738102), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
    ]
