# Generated by Django 2.2 on 2019-05-02 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20190502_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['Complaint_reply', 'Complaint_title', 'Complaint_writer', 'Complaint_writer_id', 'Complaint_writer_phone', 'Complaint_email', 'Complaint_date', 'Complaint_content'], 'verbose_name': 'شكاوى المواطنين', 'verbose_name_plural': 'شكاوى المواطنين'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 21, 58, 55, 389176), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='organization_law',
            name='law_content',
            field=models.FileField(help_text='ملف الوثيقة', upload_to='home/static/docs', verbose_name='ملف الوثيقة'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 21, 58, 55, 389176), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
    ]
