# Generated by Django 2.2 on 2019-05-02 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20190502_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح')),
                ('content', models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح')),
                ('kind', models.CharField(choices=[('option1', 'مقترحات زراعية'), ('option2', 'مقترحات صناعية'), ('option3', 'مقترحات تنموية'), ('option4', 'مقترحات خدمية'), ('option5', 'مقترحات سياحية')], max_length=100)),
            ],
            options={
                'verbose_name': 'مقترحات',
                'verbose_name_plural': 'مقترحات',
                'ordering': ['title', 'content'],
            },
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 22, 49, 2, 269830), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 22, 49, 2, 270831), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_kind',
            field=models.ForeignKey(choices=[('option1', 'مقترحات زراعية'), ('option2', 'مقترحات صناعية'), ('option3', 'مقترحات تنموية'), ('option4', 'مقترحات خدمية'), ('option5', 'مقترحات سياحية')], help_text='نوع الإقتراح', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='home.Suggestions', verbose_name='نوع الإقتراح'),
        ),
    ]
