# Generated by Django 2.2 on 2019-05-02 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20190502_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestions',
            old_name='kind',
            new_name='kind_id',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 22, 59, 32, 888631), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 22, 59, 32, 888631), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
    ]
