# Generated by Django 2.2 on 2019-05-02 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20190502_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 23, 3, 20, 701421), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 23, 3, 20, 701421), help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_kind',
            field=models.CharField(choices=[('option1', 'مقترحات زراعية'), ('option2', 'مقترحات صناعية'), ('option3', 'مقترحات تنموية'), ('option4', 'مقترحات خدمية'), ('option5', 'مقترحات سياحية')], help_text='نوع الإقتراح', max_length=100, verbose_name='نوع الإقتراح'),
        ),
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
